### ISSUE TITLE
corona_data_collector: module 'telegram' has no attribute 'Bot'

### ISSUE THREAD

**Issue by OriHoch** [hasadna/avid-covider-pipelines#2]
```
flow: Traceback (most recent call last):
flow:   File "/usr/local/lib/python3.6/dist-packages/datapackage_pipelines/specs/../lib/flow.py", line 13, in 
flow:     flow = flow_module.flow(parameters, datapackage, resources, ctx.stats)
flow:   File "/pipelines/avid_covider_pipelines/corona_data_collector_flow.py", line 9, in flow
flow:     main({'source': 'db'})
flow:   File "/pipelines/corona_data_collector/main.py", line 78, in main
flow:     db_to_file_writer = DBToFileWriter(os.path.join(os.path.dirname(__file__), f'corona_bot_answers_{day}_{month}_2020.csv'))
flow:   File "/pipelines/corona_data_collector/DBToFileWriter.py", line 68, in __init__
flow:     self.bot = telegram.Bot(token=telegram_token)
flow: AttributeError: module 'telegram' has no attribute 'Bot'
```

**Comment by YishTish** [comment]
Have you installed python-telegram-bot?

**Comment by OriHoch** [comment]
fixed by removing `telegram` dependency
